### ISSUE TITLE
Query doesn't return result when using 'is_primary_data'

### ISSUE THREAD

**Issue by sofroniewn** [chanzuckerberg/cell-census#37]
When trying the following query 

```python
import cell_census

census = cell_census.open_soma()
adata = cell_census.get_anndata(
    census,
    "Homo sapiens",
    obs_query={
        "tissue_general": "brain",
        "is_primary_data": "True", # excluding this condition the query runs fine
        "disease": "normal",
        "cell_type": ["astrocyte"],
    },
)
```

I get the following error

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [54], line 1
----> 1 adata = cell_census.get_anndata(
      2     census,
      3     "Homo sapiens",
      4     obs_query={
      5         "tissue_general": "brain",
      6         "is_primary_data": "True",
      7         "disease": "normal",
      8         "cell_type": ["astrocyte"],
      9     },
     10 )

File ~/Documents/GitHub/cell-census/api/python/cell_census/src/cell_census/get_anndata.py:119, in get_anndata(census, organism, measurement_name, X_name, obs_query, var_query, column_names)
    117 _var_query = _build_query(var_query)
    118 with experiment_query(exp, measurement_name=measurement_name, obs_query=_obs_query, var_query=_var_query) as query:
--> 119     return query.read_as_anndata(X_name=X_name, column_names=column_names)

File ~/Documents/GitHub/cell-census/api/python/cell_census/src/cell_census/experiment_query/query.py:277, in ExperimentQuery.read_as_anndata(self, X_name, column_names, X_layers)
    267 def read_as_anndata(
    268     self,
    269     X_name: str,
   (...)
    272     X_layers: Optional[List[str]] = None,
...
  /Users/nsofroniew/opt/anaconda3/envs/multiomics/lib/python3.9/concurrent/futures/thread.py(83): _worker
  /Users/nsofroniew/opt/anaconda3/envs/multiomics/lib/python3.9/threading.py(917): run
  /Users/nsofroniew/opt/anaconda3/envs/multiomics/lib/python3.9/threading.py(980): _bootstrap_inner
  /Users/nsofroniew/opt/anaconda3/envs/multiomics/lib/python3.9/threading.py(937): _bootstrap
```

If I exclude the `is_primary_data` condition the query returns fine. I get the same error if I put in a key that is not present in the `obs`.

**Comment by bkmartinjr** [comment]
This was fixed in #33

Note that it also requires a fix in TileDB and SOMA, so you will need to:
* install the latest TileDB (`pip install -U tiledb`)
* pull, and build latest SOMA
* pull, and build latest cell_census

I'll leave this open for now, at least until you have confirmed that it works.

**Comment by sofroniewn** [comment]
Ah nice - i should have looked at the closed issues too :-) will give this a try later and let you know

**Comment by bkmartinjr** [comment]
@sofroniewn - just confirming - are you still seeing this issue, or is it resolved?  I _believe_ it is resolved.

**Comment by sofroniewn** [comment]
@bkmartinjr still seeing the issue. Just tried right now updating all libraries. Unless I'm missing some build step I should be on the latest for everything

- tiledb version 0.19.0
- tiledbsoma version 0.5.0a2.dev129
- cell_census version 0.0.1-dev0

**Comment by sofroniewn** [comment]
Now I get

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [8], line 1
----> 1 adata = cell_census.get_anndata(
      2     census,
      3     "Homo sapiens",
      4     obs_query={
      5         "tissue_general": "brain",
      6         "is_primary_data": True,
      7         "disease": "normal",
      8         "cell_type": ["astrocyte"],
      9     },
     10 )

File ~/Documents/GitHub/cell-census/api/python/cell_census/src/cell_census/get_anndata.py:116, in get_anndata(census, organism, measurement_name, X_name, obs_query, var_query, column_names)
    113 if exp.soma_type != "SOMAExperiment":
    114     raise ValueError(f"Unknown organism {organism} - not a SOMA Experiment")
--> 116 _obs_query = _build_query(obs_query)
    117 _var_query = _build_query(var_query)
    118 with experiment_query(exp, measurement_name=measurement_name, obs_query=_obs_query, var_query=_var_query) as query:

File ~/Documents/GitHub/cell-census/api/python/cell_census/src/cell_census/get_anndata.py:55, in _build_query(query_defn)
     53         query_conditions.append(f"{name} in {val}")
     54     else:
---> 55         raise TypeError("Query must be string or list of strings")
     57 if len(query_conditions) == 0:
     58     return None

TypeError: Query must be string or list of strings
```

Am I stuck on an old version of cell_census without realizing it?

**Comment by sofroniewn** [comment]
Looks like I might be, I'm trying updating again

**Comment by bkmartinjr** [comment]
Yes, you are using an out of date cell_census.  Either `git pull` and rebuild, or install from `pypi` using `pip`.

**Comment by sofroniewn** [comment]
Yup, just uninstalled and reinstalled, not sure what went wrong with my first update attempt. I'm now on latest and the query is running fine (not done yet, but seems to be fetching data)

**Comment by bkmartinjr** [comment]
Thanks - I take it that things are resolved.  Closing - but feel free to re-open if not resolved.
